# Railway.app deployment configuration for Nova Titan Sports Widget

[build]
builder = "NIXPACKS"

# Backend API Service
[[services]]
name = "nova-titan-api"
source = "backend"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
PORT = "3001"

# ML Service  
[[services]]
name = "nova-titan-ml"
source = "ml"

[services.build]
buildCommand = "pip install -r requirements.txt"
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[services.variables]
ENVIRONMENT = "production"
PORT = "3002"
PYTHONUNBUFFERED = "1"

# Frontend Static Site
[[services]] 
name = "nova-titan-frontend"
source = "frontend"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npx serve -s dist -p $PORT"

[services.variables]
NODE_ENV = "production"
PORT = "3000"

# Database
[[services]]
name = "postgres"
template = "postgresql"

[[services]]
name = "redis" 
template = "redis"

# Environment Variables (set these in Railway dashboard)
# Backend:
# - DATABASE_URL (from postgres service)
# - REDIS_URL (from redis service) 
# - ML_SERVICE_URL (from ml service)
# - ODDS_API_KEY
# - JWT_SECRET
# - SENTRY_DSN
# - CORS_ORIGIN (from frontend service)

# ML Service:
# - REDIS_URL (from redis service)
# - MODEL_PATH
# - LOG_LEVEL

# Frontend:
# - VITE_API_URL (from backend service)  
# - VITE_ML_URL (from ml service)
# - VITE_SENTRY_DSN
# - VITE_GA_TRACKING_ID