/**
 * Terms of Service Component
 * Modal displaying Nova Titan Systems Terms of Service
 */

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Shield, FileText, AlertCircle } from 'lucide-react';

interface TermsOfServiceProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ isOpen, onClose }) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/50 backdrop-blur-sm"
            onClick={onClose}
          />
          
          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            className="relative bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden"
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-6">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Shield className="h-6 w-6" />
                  <div>
                    <h2 className="text-2xl font-bold">Terms of Service</h2>
                    <p className="text-blue-100 text-sm">Nova Titan Systems</p>
                  </div>
                </div>
                <button
                  onClick={onClose}
                  className="p-2 hover:bg-white/20 rounded-lg transition-colors"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
            </div>

            {/* Content */}
            <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
              <div className="prose prose-gray max-w-none">
                
                {/* Effective Date */}
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
                  <div className="flex items-center gap-2 mb-2">
                    <FileText className="h-5 w-5 text-blue-600" />
                    <span className="font-semibold text-blue-900">Effective Date: January 1, 2025</span>
                  </div>
                  <p className="text-blue-800 text-sm mb-0">
                    Last Updated: October 14, 2024 | Version 1.0
                  </p>
                </div>

                <h3 className="text-xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h3>
                <p className="text-gray-700 mb-4">
                  By accessing and using Nova Titan Elite ("the Platform"), you accept and agree to be bound by the terms and provision of this agreement. 
                  Nova Titan Systems reserves the right to modify these terms at any time.
                </p>

                <h3 className="text-xl font-bold text-gray-900 mb-4">2. Platform Description</h3>
                <p className="text-gray-700 mb-4">
                  Nova Titan Elite is an AI-powered sports analytics and prediction platform designed for educational and entertainment purposes. 
                  The platform provides sports data analysis, predictions, and betting insights but does not facilitate real money gambling.
                </p>

                <h3 className="text-xl font-bold text-gray-900 mb-4">3. Companion Mode Usage</h3>
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-4">
                  <div className="flex items-start gap-2">
                    <AlertCircle className="h-5 w-5 text-yellow-600 mt-0.5" />
                    <div>
                      <p className="text-yellow-800 font-medium mb-1">Important Notice</p>
                      <p className="text-yellow-700 text-sm mb-0">
                        This platform operates in "Companion Mode" - no real money transactions occur. 
                        All betting activities are simulated for educational purposes only.
                      </p>
                    </div>
                  </div>
                </div>

                <h3 className="text-xl font-bold text-gray-900 mb-4">4. AI Predictions Disclaimer</h3>
                <p className="text-gray-700 mb-4">
                  All predictions and analysis provided by Nova TitanAI are generated by artificial intelligence algorithms. 
                  These predictions are for informational purposes only and should not be considered as financial advice or guaranteed outcomes.
                </p>

                <h3 className="text-xl font-bold text-gray-900 mb-4">5. User Responsibilities</h3>
                <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
                  <li>You must be 18 years or older to use this platform</li>
                  <li>You are responsible for gambling responsibly if you choose to place real bets elsewhere</li>
                  <li>You acknowledge that gambling can be addictive and seek help if needed</li>
                  <li>You will not attempt to modify, extract, or tamper with Nova Titan branding or intellectual property</li>
                </ul>

                <h3 className="text-xl font-bold text-gray-900 mb-4">6. Intellectual Property</h3>
                <p className="text-gray-700 mb-4">
                  All content, logos, trademarks, and intellectual property on this platform are owned by Nova Titan Systems. 
                  The Nova Titan brand, logo, and AI algorithms are protected by copyright and trademark laws.
                </p>

                <h3 className="text-xl font-bold text-gray-900 mb-4">7. Data Usage & Privacy</h3>
                <p className="text-gray-700 mb-4">
                  We collect minimal data necessary for platform functionality. Sports odds and statistics are sourced from licensed providers. 
                  No personal gambling data is stored or transmitted in companion mode.
                </p>

                <h3 className="text-xl font-bold text-gray-900 mb-4">8. Limitation of Liability</h3>
                <p className="text-gray-700 mb-4">
                  Nova Titan Systems is not liable for any financial losses incurred based on predictions or analysis provided by this platform. 
                  Users assume all risks associated with gambling activities conducted outside of this platform.
                </p>

                <h3 className="text-xl font-bold text-gray-900 mb-4">9. Contact Information</h3>
                <p className="text-gray-700 mb-4">
                  For questions regarding these terms, contact Nova Titan Systems through our official website: 
                  <a href="https://novatitan.net/" className="text-blue-600 hover:underline ml-1">novatitan.net</a>
                </p>

                {/* Footer */}
                <div className="border-t border-gray-200 pt-4 mt-8">
                  <p className="text-center text-gray-600 font-medium">
                    © 2025 Nova Titan Systems. All rights reserved.
                  </p>
                  <p className="text-center text-gray-500 text-sm mt-1">
                    Secure. Optimize. Innovate.
                  </p>
                </div>
              </div>
            </div>

            {/* Footer Buttons */}
            <div className="bg-gray-50 px-6 py-4 border-t">
              <div className="flex items-center justify-between">
                <p className="text-sm text-gray-600">
                  By using Nova Titan Elite, you agree to these terms.
                </p>
                <button
                  onClick={onClose}
                  className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors"
                >
                  I Understand
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};